export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const PARCEL_CREATE_SUCCESS ="PARCEL_CREATE_SUCCESS";
export const PARCEL_CREATE_FAIL = "PARCEL_CREATE_FAIL";
export const PARCEL_GET_FAIL = "PARCEL_GET_FAIL";
export const PARCEL_GET_SUCCESS ="PARCEL_GET_SUCCESS";
